### ISSUE TITLE
Validate / update Gitlab recipe

### ISSUE THREAD

**Issue by funkypenguin** [funkypenguin/geek-cookbook#32]
After [reports](https://discourse.geek-kitchen.funkypenguin.co.nz/t/a-complete-gitlab-traefik-config/554) of the gitlab recipe not working any more, I'll recreate the recipe and confirm whether or not it still works with the original config, or whether it needs to be updated.

**Comment by Bencey** [comment]
Closing issue now fixed
![image](https://user-images.githubusercontent.com/33912370/41438736-647e0848-707c-11e8-8ded-aab6571f819d.png)
