### ISSUE TITLE
Add details on how to contribute

### ISSUE THREAD

**Issue by funkypenguin** [funkypenguin/geek-cookbook#5]
Readers may want to request new recipies, or contribute fixes. Add details to navigation / README to cover this

**Comment by Bencey** [comment]
Could do this if it still needs doing

**Comment by funkypenguin** [comment]
Awesome, thank you :) The place for this is https://geek-cookbook.funkypenguin.co.nz/support/ I think (support.md) - what we want is to make it obvious that PRs for feedback, new recipies etc are welcome, and than further interaction is available in the discord channels

**Comment by Bencey** [comment]
https://github.com/funkypenguin/geek-cookbook/blob/contribute/contribute.md
https://github.com/funkypenguin/geek-cookbook/tree/contribute
Done 
Closing ticket
